/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as UsunKontoRouteImport } from './routes/usun-konto'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGrupyRouteImport } from './routes/_authenticated/grupy'
import { Route as AuthenticatedNowaRouteImport } from './routes/_authenticated/nowa'
import { Route as AuthenticatedPowiadomieniaRouteImport } from './routes/_authenticated/powiadomienia'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedZaproszeniaRouteImport } from './routes/_authenticated/zaproszenia'
import { Route as AuthenticatedZglosFotoradarRouteImport } from './routes/_authenticated/zglos-fotoradar'
import { Route as MotocyklistaIdRouteImport } from './routes/motocyklista.$id'
import { Route as WyprawaIdRouteImport } from './routes/wyprawa.$id'
import { Route as AuthenticatedEdytujIdRouteImport } from './routes/_authenticated/edytuj.$id'
import { Route as AuthenticatedGrupaIdRouteImport } from './routes/_authenticated/grupa.$id'
import { Route as ApiPublicAccountDeletionFinishRouteImport } from './routes/api/public/account-deletion-finish'
import { Route as ApiPublicRideAlertsRouteImport } from './routes/api/public/ride-alerts'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const UsunKontoRoute = UsunKontoRouteImport.update({
  id: '/usun-konto',
  path: '/usun-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrupyRoute = AuthenticatedGrupyRouteImport.update({
  id: '/grupy',
  path: '/grupy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNowaRoute = AuthenticatedNowaRouteImport.update({
  id: '/nowa',
  path: '/nowa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPowiadomieniaRoute =
  AuthenticatedPowiadomieniaRouteImport.update({
    id: '/powiadomienia',
    path: '/powiadomienia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZaproszeniaRoute =
  AuthenticatedZaproszeniaRouteImport.update({
    id: '/zaproszenia',
    path: '/zaproszenia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZglosFotoradarRoute =
  AuthenticatedZglosFotoradarRouteImport.update({
    id: '/zglos-fotoradar',
    path: '/zglos-fotoradar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MotocyklistaIdRoute = MotocyklistaIdRouteImport.update({
  id: '/motocyklista/$id',
  path: '/motocyklista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WyprawaIdRoute = WyprawaIdRouteImport.update({
  id: '/wyprawa/$id',
  path: '/wyprawa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEdytujIdRoute = AuthenticatedEdytujIdRouteImport.update({
  id: '/edytuj/$id',
  path: '/edytuj/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrupaIdRoute = AuthenticatedGrupaIdRouteImport.update({
  id: '/grupa/$id',
  path: '/grupa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAccountDeletionFinishRoute =
  ApiPublicAccountDeletionFinishRouteImport.update({
    id: '/api/public/account-deletion-finish',
    path: '/api/public/account-deletion-finish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRideAlertsRoute = ApiPublicRideAlertsRouteImport.update({
  id: '/api/public/ride-alerts',
  path: '/api/public/ride-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ranking': typeof RankingRoute
  '/usun-konto': typeof UsunKontoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/grupy': typeof AuthenticatedGrupyRoute
  '/nowa': typeof AuthenticatedNowaRoute
  '/powiadomienia': typeof AuthenticatedPowiadomieniaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/zaproszenia': typeof AuthenticatedZaproszeniaRoute
  '/zglos-fotoradar': typeof AuthenticatedZglosFotoradarRoute
  '/motocyklista/$id': typeof MotocyklistaIdRoute
  '/wyprawa/$id': typeof WyprawaIdRoute
  '/edytuj/$id': typeof AuthenticatedEdytujIdRoute
  '/grupa/$id': typeof AuthenticatedGrupaIdRoute
  '/api/public/account-deletion-finish': typeof ApiPublicAccountDeletionFinishRoute
  '/api/public/ride-alerts': typeof ApiPublicRideAlertsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ranking': typeof RankingRoute
  '/usun-konto': typeof UsunKontoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/grupy': typeof AuthenticatedGrupyRoute
  '/nowa': typeof AuthenticatedNowaRoute
  '/powiadomienia': typeof AuthenticatedPowiadomieniaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/zaproszenia': typeof AuthenticatedZaproszeniaRoute
  '/zglos-fotoradar': typeof AuthenticatedZglosFotoradarRoute
  '/motocyklista/$id': typeof MotocyklistaIdRoute
  '/wyprawa/$id': typeof WyprawaIdRoute
  '/edytuj/$id': typeof AuthenticatedEdytujIdRoute
  '/grupa/$id': typeof AuthenticatedGrupaIdRoute
  '/api/public/account-deletion-finish': typeof ApiPublicAccountDeletionFinishRoute
  '/api/public/ride-alerts': typeof ApiPublicRideAlertsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ranking': typeof RankingRoute
  '/usun-konto': typeof UsunKontoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/grupy': typeof AuthenticatedGrupyRoute
  '/_authenticated/nowa': typeof AuthenticatedNowaRoute
  '/_authenticated/powiadomienia': typeof AuthenticatedPowiadomieniaRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/zaproszenia': typeof AuthenticatedZaproszeniaRoute
  '/_authenticated/zglos-fotoradar': typeof AuthenticatedZglosFotoradarRoute
  '/motocyklista/$id': typeof MotocyklistaIdRoute
  '/wyprawa/$id': typeof WyprawaIdRoute
  '/_authenticated/edytuj/$id': typeof AuthenticatedEdytujIdRoute
  '/_authenticated/grupa/$id': typeof AuthenticatedGrupaIdRoute
  '/api/public/account-deletion-finish': typeof ApiPublicAccountDeletionFinishRoute
  '/api/public/ride-alerts': typeof ApiPublicRideAlertsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ranking'
    | '/usun-konto'
    | '/admin'
    | '/grupy'
    | '/nowa'
    | '/powiadomienia'
    | '/profil'
    | '/zaproszenia'
    | '/zglos-fotoradar'
    | '/motocyklista/$id'
    | '/wyprawa/$id'
    | '/edytuj/$id'
    | '/grupa/$id'
    | '/api/public/account-deletion-finish'
    | '/api/public/ride-alerts'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ranking'
    | '/usun-konto'
    | '/admin'
    | '/grupy'
    | '/nowa'
    | '/powiadomienia'
    | '/profil'
    | '/zaproszenia'
    | '/zglos-fotoradar'
    | '/motocyklista/$id'
    | '/wyprawa/$id'
    | '/edytuj/$id'
    | '/grupa/$id'
    | '/api/public/account-deletion-finish'
    | '/api/public/ride-alerts'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ranking'
    | '/usun-konto'
    | '/_authenticated/admin'
    | '/_authenticated/grupy'
    | '/_authenticated/nowa'
    | '/_authenticated/powiadomienia'
    | '/_authenticated/profil'
    | '/_authenticated/zaproszenia'
    | '/_authenticated/zglos-fotoradar'
    | '/motocyklista/$id'
    | '/wyprawa/$id'
    | '/_authenticated/edytuj/$id'
    | '/_authenticated/grupa/$id'
    | '/api/public/account-deletion-finish'
    | '/api/public/ride-alerts'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RankingRoute: typeof RankingRoute
  UsunKontoRoute: typeof UsunKontoRoute
  MotocyklistaIdRoute: typeof MotocyklistaIdRoute
  WyprawaIdRoute: typeof WyprawaIdRoute
  ApiPublicAccountDeletionFinishRoute: typeof ApiPublicAccountDeletionFinishRoute
  ApiPublicRideAlertsRoute: typeof ApiPublicRideAlertsRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usun-konto': {
      id: '/usun-konto'
      path: '/usun-konto'
      fullPath: '/usun-konto'
      preLoaderRoute: typeof UsunKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupy': {
      id: '/_authenticated/grupy'
      path: '/grupy'
      fullPath: '/grupy'
      preLoaderRoute: typeof AuthenticatedGrupyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nowa': {
      id: '/_authenticated/nowa'
      path: '/nowa'
      fullPath: '/nowa'
      preLoaderRoute: typeof AuthenticatedNowaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/powiadomienia': {
      id: '/_authenticated/powiadomienia'
      path: '/powiadomienia'
      fullPath: '/powiadomienia'
      preLoaderRoute: typeof AuthenticatedPowiadomieniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zaproszenia': {
      id: '/_authenticated/zaproszenia'
      path: '/zaproszenia'
      fullPath: '/zaproszenia'
      preLoaderRoute: typeof AuthenticatedZaproszeniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zglos-fotoradar': {
      id: '/_authenticated/zglos-fotoradar'
      path: '/zglos-fotoradar'
      fullPath: '/zglos-fotoradar'
      preLoaderRoute: typeof AuthenticatedZglosFotoradarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/motocyklista/$id': {
      id: '/motocyklista/$id'
      path: '/motocyklista/$id'
      fullPath: '/motocyklista/$id'
      preLoaderRoute: typeof MotocyklistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyprawa/$id': {
      id: '/wyprawa/$id'
      path: '/wyprawa/$id'
      fullPath: '/wyprawa/$id'
      preLoaderRoute: typeof WyprawaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/edytuj/$id': {
      id: '/_authenticated/edytuj/$id'
      path: '/edytuj/$id'
      fullPath: '/edytuj/$id'
      preLoaderRoute: typeof AuthenticatedEdytujIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupa/$id': {
      id: '/_authenticated/grupa/$id'
      path: '/grupa/$id'
      fullPath: '/grupa/$id'
      preLoaderRoute: typeof AuthenticatedGrupaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/account-deletion-finish': {
      id: '/api/public/account-deletion-finish'
      path: '/api/public/account-deletion-finish'
      fullPath: '/api/public/account-deletion-finish'
      preLoaderRoute: typeof ApiPublicAccountDeletionFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ride-alerts': {
      id: '/api/public/ride-alerts'
      path: '/api/public/ride-alerts'
      fullPath: '/api/public/ride-alerts'
      preLoaderRoute: typeof ApiPublicRideAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGrupyRoute: typeof AuthenticatedGrupyRoute
  AuthenticatedNowaRoute: typeof AuthenticatedNowaRoute
  AuthenticatedPowiadomieniaRoute: typeof AuthenticatedPowiadomieniaRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedZaproszeniaRoute: typeof AuthenticatedZaproszeniaRoute
  AuthenticatedZglosFotoradarRoute: typeof AuthenticatedZglosFotoradarRoute
  AuthenticatedEdytujIdRoute: typeof AuthenticatedEdytujIdRoute
  AuthenticatedGrupaIdRoute: typeof AuthenticatedGrupaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGrupyRoute: AuthenticatedGrupyRoute,
  AuthenticatedNowaRoute: AuthenticatedNowaRoute,
  AuthenticatedPowiadomieniaRoute: AuthenticatedPowiadomieniaRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedZaproszeniaRoute: AuthenticatedZaproszeniaRoute,
  AuthenticatedZglosFotoradarRoute: AuthenticatedZglosFotoradarRoute,
  AuthenticatedEdytujIdRoute: AuthenticatedEdytujIdRoute,
  AuthenticatedGrupaIdRoute: AuthenticatedGrupaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RankingRoute: RankingRoute,
  UsunKontoRoute: UsunKontoRoute,
  MotocyklistaIdRoute: MotocyklistaIdRoute,
  WyprawaIdRoute: WyprawaIdRoute,
  ApiPublicAccountDeletionFinishRoute: ApiPublicAccountDeletionFinishRoute,
  ApiPublicRideAlertsRoute: ApiPublicRideAlertsRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
