/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NowaRouteImport } from './routes/nowa'
import { Route as WyprawaIdRouteImport } from './routes/wyprawa.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NowaRoute = NowaRouteImport.update({
  id: '/nowa',
  path: '/nowa',
  getParentRoute: () => rootRouteImport,
} as any)
const WyprawaIdRoute = WyprawaIdRouteImport.update({
  id: '/wyprawa/$id',
  path: '/wyprawa/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nowa': typeof NowaRoute
  '/wyprawa/$id': typeof WyprawaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nowa': typeof NowaRoute
  '/wyprawa/$id': typeof WyprawaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nowa': typeof NowaRoute
  '/wyprawa/$id': typeof WyprawaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nowa' | '/wyprawa/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nowa' | '/wyprawa/$id'
  id: '__root__' | '/' | '/nowa' | '/wyprawa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NowaRoute: typeof NowaRoute
  WyprawaIdRoute: typeof WyprawaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nowa': {
      id: '/nowa'
      path: '/nowa'
      fullPath: '/nowa'
      preLoaderRoute: typeof NowaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyprawa/$id': {
      id: '/wyprawa/$id'
      path: '/wyprawa/$id'
      fullPath: '/wyprawa/$id'
      preLoaderRoute: typeof WyprawaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NowaRoute: NowaRoute,
  WyprawaIdRoute: WyprawaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
